### ISSUE TITLE
User can grant access to wallet to other users

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/btcpayserver#14]
Basically a user should be able to open up access to their wallet and share it with other users.

Inspired by recent feedback and btcpayserver/btcpayserver#3660

**Comment by damanic** [comment]
I just came across this limitation, good to see there is already a open ticket for the feature.  

The tagged discussion matches my issue exactly.

+1  
We need a store assigned LNBANK wallet to be accessible to store users.

**Comment by dennisreimann** [comment]
Done with v1.3.0
