### ISSUE TITLE
Payment is received in LNBank, but BTCPay invoice is not settled

### ISSUE THREAD

**Issue by iBobik** [dennisreimann/btcpayserver#18]
**Plugin**
LNbank

**Describe the bug**
When invoices are created by Pay Button (public invoice API) they are not settled when payment to LNBank was received. 

Private Invoices API works

**To Reproduce the bug**
Steps to reproduce the reported bug:

1. Have LNBank for a store
2. Create Invoice by Pay Button, New invoice or POS app
3. Pay LN invoice (BOLT or LNURL)
4. See it send in your walled, received in a LNBank wallet, but Invoice in a New state and payment dialog is still waiting for it. 

Change store Lightning backend to Internal node and it will work (invoices are settled).

**Expected behavior**

BTCPay invoices are settled even with LNBank wallet.

**Screenshots**

<img width="881" alt="Snímek obrazovky 2022-07-02 v 2 24 45" src="https://user-images.githubusercontent.com/614232/176979759-2d279c11-af68-4405-bea6-45266b059b6a.png">
<img width="929" alt="Snímek obrazovky 2022-07-02 v 2 23 03" src="https://user-images.githubusercontent.com/614232/176979762-6d53fcd9-c97e-414b-85e7-c3d99ffa1a6a.png">
<img width="699" alt="Snímek obrazovky 2022-07-02 v 2 22 47" src="https://user-images.githubusercontent.com/614232/176979763-f986f315-7512-4e46-97d5-ef2a1b4b1f67.png">
<img width="922" alt="Snímek obrazovky 2022-07-02 v 2 22 14" src="https://user-images.githubusercontent.com/614232/176979764-f31bf122-13e7-4050-a93c-2eb65266cad2.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.5.4.0
- Plugin Name and Version   LNbank 1.2.2.0
- Deployment Method:        Docker
- Browser:                  Safari

**Logs (if applicable)**

```
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 5 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Invalidated transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Settled transaction 569e4561-4279-42a9-85ee-66ffc48db2bd
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 4 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve invoice (Invoice Id = 6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8) for transaction dff533bf-f31e-479d-8dc1-51242b7e0b3a - invalidating transaction
```

**Comment by dennisreimann** [comment]
What is the underlying implementation (LND, Core Lightning) of the node that hosts the LNbank wallet? Do you have the ability to find out (e.g. via RTL, Thunderhub or CLI) if there is the invoice with ID `6be5cec344be5736fec84ea49a9a27636000a340299ed83ebc1267b0b693e8c8` and if so, what the status of that invoice is?

**Comment by iBobik** [comment]
Hi, it is LND.

I found that invoice in the RTL, the state is CANCELED.


Honza Pobořil


4. 7. 2022 17:07:42, d11n ***@***.***> napsal:

**Comment by dennisreimann** [comment]
The invoice must have been cancelled from another app or the counterparty then. LNbank does not cancel invoices. 

Can you upgrade to BTCPay v1.6 and LNbank v1.2.3 and see if this works for you?

**Comment by iBobik** [comment]
Upgraded all, now it is working.

Thank you for support :-)

**Comment by iBobik** [comment]
Hi,
I’ve upgraded to 1.6.3 and now it is the same broken also for internal
connection.

I see it in RTL like normal settled transaction or like two invoices with
the same amount - first has memo and is cancelled, second is settled,
without memo, few minutes later. Both are in a new state in BtcPay.


Honza Pobořil


10. 7. 2022 18:26:24, d11n ***@***.***> napsal:

**Comment by dennisreimann** [comment]
Can you provide the BTCPay logs for the timeframe in which this happened?

**Comment by iBobik** [comment]
It was happening whole day and also tested it right now. Log is full of
this errors:

fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher:
Checking pending transaction 75dfc9f3-8b3d-4289-8e55-c14076179ad4 failed:
payment isn't initiated

BTCPayServer.Lightning.LND.LndException: payment isn't initiated

   at
BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.ListenLoop(HttpRequestMessage
request)

   at
BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.WaitPayment(CancellationToken
cancellation)

   at
BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetPayment(String
paymentHash, CancellationToken cancellation)

   at
BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetPayment(String
cryptoCode, String paymentHash, CancellationToken cancellationToken) in
/source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line
199

   at
BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningPayment(String
cryptoCode, String paymentHash, CancellationToken token) in
/source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line
1005

   at
BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningPayment(String
paymentHash, CancellationToken cancellationToken) in
/home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line
47

   at
BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPendingTransaction(WalletService
walletService, Transaction transaction, CancellationToken
cancellationToken) in
/home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line
101

info: PayServer:      BTC (Lightning): Payment detected via notification
(Pf9vyWaTRyjjBTL1zxijoF)

info: PayServer:      BTC (Lightning): No more invoice to listen on
http://lnd_bitcoin:8080/, releasing the connection.

But I switched to internal node again and now it works, so issue happens
only with LNbank now.

Honza Pobořil


2. 8. 2022 0:32:38, d11n ***@***.***> napsal:

**Comment by dennisreimann** [comment]
Is this an outgoing payment made from a LNbank wallet? Is it paying the same node maybe?

**Comment by iBobik** [comment]
No, this are incoming invoices created by Pay button API.

Honza Pobořil
💬Signal

**Comment by dennisreimann** [comment]
The log you posted must be unrelated then, because that excerpt is from an outgoing payment, not an incoming one.

I just checked and in general it seems to be working with the pay button, so we need to dig deeper here I fear :|

**Comment by dennisreimann** [comment]
Can you reactivate it, try it again and send the log if it isn't working?

**Comment by iBobik** [comment]
I've upgraded to 1.6.6, tried to switch store to LNBank, to internal, and back, did payments in all setups and all of them were settled correctly.

So some latest bug fix solved it, or is brakes later after restart.

**Comment by dennisreimann** [comment]
Ok, thanks. Let's keep an eye on this. Thanks again for your feedback!

**Comment by iBobik** [comment]
Thank you for your help. :-)


Honza Pobořil


8. 8. 2022 22:39:39, d11n ***@***.***> napsal:
